### ISSUE TITLE
Add PropTypes

### ISSUE THREAD

**Issue by EricTurf** [EricTurf/react-sudoku#68]
Add PropTypes to all components as a `static` property on the class

IE
```javascript

class Thing extends React.Component {
       static propTypes={ ... };

}

```

**Comment by tudorpavel** [comment]
Hi, I could help with this. However, I can't seem to run the project, there is no `scripts/` folder to run `node scripts/start.js` from. Has the project setup changed from what is written in the README?

**Comment by tudorpavel** [comment]
@EricTurf PRs submitted for this issue and for project setup updates.

Happy Hacktoberfest!

**Comment by tudorpavel** [comment]
Huh, the keyboard works only sometimes for me. I'm not sure why, I'm on Ubuntu with Chrome 69. I think I'll investigate this tomorrow, I'm curious why the `keyup` event doesn't always trigger...

**Comment by tudorpavel** [comment]
I realized why my keyboard inputs where working only sometimes... It was because of the [Vimium](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=en) extension which listens for certain keys on `document` as well, doh! I usually have this problem with browser games when I forget to disable Vimium.

In case of react-sudoku, I guess the squares could be rendered as styled inputs too but it's just a different design choice.

**Comment by EricTurf** [comment]
@tudorpavel Ya I wasn't really a fan of the idea of having them be inputs mostly because I find it ugly if there is a cursor to type things when you go to input something :P
